[phases.setup]
nixPkgs = ["cargo", "rustc", "gcc", "openssl.dev", "pkg-config", "make"]

[phases.build]
cmds = [
  "cargo build --release"
]

[start]
cmd = "./target/release/solana-pumpfun-sniper-bot"
