[phases.setup]
nixPkgs = ["cargo", "rustc", "gcc", "openssl", "pkg-config", "make", "cmake"]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/solana-pumpfun-sniper-bot"
